import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="text-lg md:text-xl lg:text-5xl : p-3 : bg-gray-100">     { /*메인 내비게이션  tailwind 사용한 css*/ }
          <Link href="/"> 홈 </Link>
          <Link href="/subject"> 과목 </Link>
          <Link href="/record"> 기록 </Link>
          <Link href="/quiz"> 퀴즈 </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
